### ISSUE TITLE
Great product, Several questions

### ISSUE THREAD

**Issue by gpsamson** [ory-am/ladon#38]
First off, huge props to the ory-am team behind Ladon. You guys are putting together a great product and I hope to contribute in the future. I came across Ladon while looking for authentication and authorization solutions for a new product at work. Originally I was considering Hydra, but Oauth seemed too bloated and complicated for the first few versions. We decided to use JWTs for authentication because they're simple and stateless. However, authorization is still up in the air and we're leaning towards Ladon, but we have a few questions before we get cooking and start rolling out tests with Ladon.

How production ready is Ladon in its current state?  Are there any big changes planned for Ladon in the next year?

Is containerizing possible with AWS Elasticache persistance? I plan to containerize Ladon and do a little rewriting to store policies in AWS Elasticache instead of the machines/containers memory. 

Does Ladon allow policy variables, similar to AWS? If not, how difficult would it be to implement? (http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html) The goal of policy variables is to avoid the need to create a policy for every new user or resource.

Are there any examples with a REST request endpoint besides the curl script? With my understanding of the codebase, it should be as easy as defining a POST endpoint that implements Warden.

Forgive me if this write up is a little long. I would much rather ask the questions now before I invest several hours into understanding and forking the repo.

Excited to dive deeper into the possibilities of Ladon! Huge thank you to anyone who is happy to respond.

**Comment by arekkas** [comment]
Thank you for the kind words!

> How production ready is Ladon in its current state? Are there any big changes planned for Ladon in the next year?

Although it is not tagged as stable, there has not been any major breaks in the last 6 months. Ladon is being used in production on various systems and we have not seen any problems there. Thus, no big changes are planned, apart from extending the current feature set when it comes to conditions.

> Is containerizing possible with AWS Elasticache persistance? I plan to containerize Ladon and do a little rewriting to store policies in AWS Elasticache instead of the machines/containers memory. 

Yes to both questions, the architecture was written in a way to make extension of storage adapters as easy as possible.

> Are there any examples with a REST request endpoint besides the curl script? With my understanding of the codebase, it should be as easy as defining a POST endpoint that implements Warden.

Your understanding is correct. There are no other examples apart from the ones in the README.

> Does Ladon allow policy variables, similar to AWS? If not, how difficult would it be to implement? (http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html) The goal of policy variables is to avoid the need to create a policy for every new user or resource.

Yes and no. Yes, because it is supported by policy conditions and no, because the request to ladon must be filled with the variables that you need. I think the CIDR IP Address in the example is a good example of how this works: https://github.com/ory-am/ladon#cidr-condition

> Forgive me if this write up is a little long. I would much rather ask the questions now before I invest several hours into understanding and forking the repo.

All good, I know this position all too well and it's nice when maintainers answer those questions. You can also join our gitter channel: https://gitter.im/ory-am/hydra?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

By the way, we are offering paid support, in case you come across any major hurtles or need some help beyond the basic support here on github/gitter.

**Comment by gpsamson** [comment]
Thanks for the response arekkas. I sat down with another lead on the product and we're going with Ladon to handle policy and authorization of a much bigger service that similar to AWS IAM. We're planning to write a Redis manager and additional conditions as we see fit. Excited to contribute. I will be joining gitter in the coming weeks as a dive into the codebase and test use cases.

Again, thanks for the help. I appreciate it.

**Comment by arekkas** [comment]
Awesome, looking forward :)
