### ISSUE TITLE
Very cool looking project!

### ISSUE THREAD

**Issue by bketelsen** [ory-am/ladon#7]
how about an intro post on the GopherAcademy December blog post series?

https://docs.google.com/spreadsheets/d/1H0rj7TJo0t8GWyNdGwEc6bGcDj6UgJUN42JtAtbPMrk/edit?usp=sharing

I've been following this and your other auth related projects with curiosity lately.  Can't wait to see what comes of them.

Brian

**Comment by arekkas** [comment]
Thanks so much for the link, I didn't know a public list exists! Everything is still under heavy development but it's in the finishing touches. Is this list going to go onwards in 2016? Because we wanted to test Hydra and it's related libraries under real world conditions. As things are looking now I think we'll be able to ship Hydra with good docs, more tests and real world use in early Q1 2016.

I think it's about time that an open source alternative to auth0.com and oauth.io for the micro service oriented world pops up. These services are great but one really commits to those heavy pricing models. I've been pounding all my life against AuthZ and AuthN. Everytime you have to do it it's a pain because there just so many things that can go wrong.

I believe that the Go Community, with a little initiation, can achieve a highly popular, well tested and real-world-applied AuthX server.

I hope I can achieve this sort of initiation, even though a lot of functionality (SAML, LDAP, ...) is still missing.

I'm really glad that you're interested in the project, I have done a lot of stuff but never received the traction I did in the last couple of weeks. So thank you! :)

**Comment by arekkas** [comment]
Thank you for encouraging me to write the blog post. The response has truly been amazing. I'd be happy to participate again next time, I think I have some other cool things to show :)
